export const USER_DATA_REQUEST= 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';


export const USER_DELETION_REQUEST= 'USER_DELETION_REQUEST';
export const USER_DELETION_SUCCESS = 'USER_DELETION_SUCCESS';
export const USER_DELETION_FAIL = 'USER_DELETION_FAIL';



export const USER_ADDITION_REQUEST= 'USER_ADDITION_REQUEST';
export const USER_ADDITION_SUCCESS = 'USER_ADDITION_SUCCESS';
export const USER_ADDITION_FAIL = 'USER_ADDITION_FAIL';



export const USER_UPDATE_REQUEST= 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

